@url=http://127.0.0.1:8000/
### get
get http://127.0.0.1:8000/json/url.json
### get
get {{url}}names/abc

### post name 
post {{url}}names
Content-Type: application/json

{
    "name": "ab",
    "age": 8
}

### put edit 

put {{url}}names/abc
Content-Type: application/json

{
   "name": "qq"
}

### del

DELETE {{url}}names/ab